import A5O
#print axioms O_unique
#print axioms quorum_two_governors
#print axioms quorum_not_CFunctional
#print axioms P1
#print axioms P3
#print axioms P4
#print axioms P5
#print axioms N1_necessity
#print axioms N2_necessity
#print axioms N3_necessity
#print axioms N4_necessity
#print axioms N5_necessity
#print axioms N6_necessity
#print axioms U3_reduction
#print axioms canonical_monitor_achieves_ADA
#print axioms canonical_monitor_is_complete
#print axioms overcautious_monitor_achieves_ADA
#print axioms completeness_is_not_universal
#print axioms ABLP.ablp_predicates_are_time_invariant
#print axioms ABLP.revocation_dominance_requires_time_variance
#print axioms ABLP.D1_no_revocation_dominance_primitive
#print axioms ABLP.ablp_predicates_are_action_invariant
#print axioms ABLP.particularity_requires_action_variance
#print axioms ABLP.D2_not_act_specific
#print axioms ABLP.D3_compound_principals_violate_single_governor
#print axioms SPKI.spki_certs_can_vary_over_time
#print axioms SPKI.spki_certs_can_vary_over_action
#print axioms SPKI.SPKI_threshold_violates_single_governor
#print axioms Macaroons.bearer_tokens_admit_multiple_governors
#print axioms Biscuit.biscuit_chain_integrity_matches_C_functional
#print axioms UCAN.ucan_matches_P2_shape
#print axioms revoked_defeats_O
#print axioms revocation_blocks_enforcement
