import PeriodicTable
open A5O.Periodic
#print axioms sum_is_iron
#print axioms formula_is_californium
#print axioms exponent_is_boron
#print axioms iron_only_under_argon
#print axioms group_gap
#print axioms five_d_orbitals
#print axioms shellCap_eq
#print axioms shell_one_has_two
#print axioms no_third_electron
#print axioms periods_are_shell_capacities
#print axioms noble_gas_numbers
#print axioms argon_closes_period_three
#print axioms oganesson_closes_the_table
#print axioms iron_is_argon_core_plus_eight
#print axioms three_inversions
#print axioms weight_order_misplaces
#print axioms Z_order_places
#print axioms argon_third_in_air
#print axioms argon_is_0_93_percent
#print axioms air_is_about_one_fifth_oxidizer
#print axioms rayleigh_residue
#print axioms column_filled_in_four_years
#print axioms potassium_argon_clock
#print axioms oxygen_doubly_magic
#print axioms nucleon_step_lands_in_gap
#print axioms alpha_step_lands_in_gap
#print axioms triple_alpha_clears_both
#print axioms then_oxygen
#print axioms echo_is_numeral_only
#print axioms hoyle_state
#print axioms ladder_positions
#print axioms ladder_ends_in_iron
#print axioms nickel62_tops_binding
#print axioms iron56_lowest_mass_per_nucleon
#print axioms collapse_then_caught
#print axioms direct_reaction_forbidden
#print axioms iron_opens_a_path
#print axioms path_iff_unpaired
#print axioms five_bonds
#print axioms one_open_seat
#print axioms four_plus_one
#print axioms seat_is_exclusive
#print axioms reversible_in_pocket
#print axioms bare_heme_is_ruined
#print axioms impostor_blocks_oxygen
#print axioms pocket_discrimination
#print axioms reporting_reaches_three
#print axioms gated_never_leaks
#print axioms ungated_partial_leaks
#print axioms same_end_state
#print axioms four_electron_balance
#print axioms sink_holds
#print axioms sink_filled
#print axioms scram_is_fail_closed
#print axioms source_initiates
#print axioms initiator_and_terminator
#print axioms point_nucleus_limit
#print axioms known_table_inside_both_limits
#print axioms fives_agree_in_count
#print axioms both_land_in_five_places
#print axioms asListed_injective
#print axioms swapped_injective
#print axioms notation_forces_no_mapping
