import DeploymentTests
set_option autoImplicit false

-- Generated theorem audit. Output must be inspected, not presumed empty.
#print axioms O_unique
#print axioms quorum_two_governors
#print axioms quorum_not_CFunctional
#print axioms P1
#print axioms P3
#print axioms P4
#print axioms P5
#print axioms N1_necessity
#print axioms N2_necessity
#print axioms N3_necessity
#print axioms N4_necessity
#print axioms N5_necessity
#print axioms N6_necessity
#print axioms U3_reduction
#print axioms canonical_monitor_achieves_ADA
#print axioms canonical_monitor_is_complete
#print axioms overcautious_monitor_achieves_ADA
#print axioms completeness_is_not_universal
#print axioms ABLP.ablp_predicates_are_time_invariant
#print axioms ABLP.revocation_dominance_requires_time_variance
#print axioms ABLP.D1_no_revocation_dominance_primitive
#print axioms ABLP.ablp_predicates_are_action_invariant
#print axioms ABLP.particularity_requires_action_variance
#print axioms ABLP.D2_not_act_specific
#print axioms ABLP.D3_compound_principals_violate_single_governor
#print axioms SPKI.spki_certs_can_vary_over_time
#print axioms SPKI.spki_certs_can_vary_over_action
#print axioms SPKI.SPKI_threshold_violates_single_governor
#print axioms Macaroons.bearer_tokens_admit_multiple_governors
#print axioms Biscuit.biscuit_chain_integrity_matches_C_functional
#print axioms UCAN.ucan_matches_P2_shape
#print axioms revoked_defeats_O
#print axioms revocation_blocks_enforcement
#print axioms Occurrence.descriptive_a0
#print axioms Occurrence.appointed_L1
#print axioms Occurrence.not_appointed_L0
#print axioms Occurrence.appointment_not_artifact_derivable
#print axioms Occurrence.five_not_appointment
#print axioms Occurrence.bearer_witness
#print axioms Occurrence.artifact_only_authorizes_unappointed
#print axioms Occurrence.sound_authorizer_not_artifact_only
#print axioms Occurrence.appointment_precedes_check
#print axioms Occurrence.O_is_five_and_app
#print axioms Occurrence.five_a0
#print axioms Occurrence.not_app_a0
#print axioms Occurrence.v4_appointment_independent
#print axioms gated_sufficiency
#print axioms ungated_ADA_does_not_suffice
#print axioms silent_not_gatable
#print axioms Apertures.allPass_iff
#print axioms Apertures.decision_sound
#print axioms Apertures.invalid_request_denied
#print axioms Apertures.no_identity_denied
#print axioms Apertures.no_binding_denied
#print axioms Apertures.no_mandate_denied
#print axioms Apertures.no_scope_denied
#print axioms Apertures.revoked_request_denied
#print axioms Apertures.no_appointment_denied
#print axioms Apertures.gate_intercepts
#print axioms Apertures.gate_achievesADA
#print axioms Apertures.trace_accountable
#print axioms Apertures.apertures_accountable
#print axioms Apertures.deny_not_executed
#print axioms Apertures.Tests.checks_sound
#print axioms Apertures.Tests.allow_decision
#print axioms Apertures.Tests.revocation_denies
#print axioms Apertures.Tests.appointment_before_start_denies
#print axioms Apertures.Tests.demo_decisions
#print axioms Apertures.Tests.demo_coverage
#print axioms Apertures.Tests.demo_unique_ids
#print axioms Apertures.Tests.allow_executed
#print axioms Apertures.Tests.allow_satisfies_O
#print axioms Apertures.Tests.nonvacuous_model_exists
#print axioms Apertures.Tests.synthetic_accountability
#print axioms Apertures.Tests.deny_receipt_cannot_match_execution
#print axioms Apertures.Tests.missing_binding_denies
#print axioms Apertures.Tests.missing_identity_denies
#print axioms Apertures.Tests.missing_mandate_denies
#print axioms Apertures.Tests.missing_scope_denies
#print axioms Apertures.Tests.missing_revocation_denies
#print axioms Apertures.Tests.missing_appointment_denies
#print axioms Apertures.Tests.all_six_have_failing_cases
#print axioms Apertures.Tests.wrong_request_id_rejected
#print axioms Apertures.Tests.wrong_agent_rejected
#print axioms Apertures.Tests.wrong_action_rejected
#print axioms Apertures.Tests.wrong_time_rejected
#print axioms Apertures.Tests.phantom_not_listed
#print axioms Apertures.Tests.phantom_not_executed
#print axioms Apertures.Tests.bypass_violates_coverage
#print axioms Apertures.Tests.forged_trace_has_coverage
#print axioms Apertures.Tests.forged_allow_fails_checker_fidelity
#print axioms Apertures.Tests.trace_coverage_is_not_real_world_coverage
#print axioms Apertures.Tests.lying_checks_not_sound
#print axioms Apertures.Tests.ambiguous_trace_coverage
#print axioms Apertures.Tests.ambiguous_ids_not_unique
#print axioms Apertures.Tests.deny_can_match_without_unique_ids
